[package]
name = "plexo-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plexo-sdk = "0.1.0"
tokio = { version = "1.34.0", features = ["full"] }
async-graphql = { version = "6.0.11", features = [
    "decimal",
    "chrono",
    "dataloader",
    "uuid",
] }
uuid = "1.5.0"
chrono = "0.4.31"
